monoped: #namespace

    #qlearn parameters
    task_and_robot_environment_name: 'HopperStayUp-v0'
    alpha: 0.1
    epsilon: 0.9
    gamma: 0.7
    epsilon_discount: 0.999
    nepisodes: 500
    nsteps: 10000

